### ISSUE TITLE
Broken link on front README page

### ISSUE THREAD

**Issue by mhucka** [caltechlibrary/AuthorCarpentry#13]
The top-level README.md (and thus the front page of this repository) has a link to "Greg Wilson's draft lesson Modern Scientific Authoring", but the link is broken.

**Comment by rsdoiel** [comment]
Hello,

We're rebooting our AuthorCarpentry efforts and are migrating to  https://github.com/AuthorCarpentry. I'm closing this issue as part of migrating the project to its own organization.

Thank you,

Robert
