### ISSUE TITLE
Template link in contribution guidelines broken

### ISSUE THREAD

**Issue by nuest** [caltechlibrary/AuthorCarpentry#14]
The link to a new lesson template in https://github.com/caltechlibrary/AuthorCarpentry/blob/master/Contributing.md#our-template is broken

**Comment by rsdoiel** [comment]
Hello,

We are migrating this to the new Github organization for AuthorCarpentry at  https://github.com/AuthorCarpentry. I am closing this issue as part of that migration.

Thank you,

Robert
