### ISSUE TITLE
Lesson on using containers to encapsulate research environments

### ISSUE THREAD

**Issue by nuest** [caltechlibrary/AuthorCarpentry#15]
We're a [small research project](http://o2r.info/) working on containerization of research using Docker. I really like your efforts here and wonder if you'd welcome a contribution of a lesson on how to use containers (instead of say, VMs or workflow languages) for a well-defined runtime environment when running an analysis.

I would estimate such a lesson could introduce novice users to run a script of their favourite programming language in a container, and run a couple of analysis environments (Jupyter Notebook, RStudio, ...) within 2-3 hours.

Docker is available for all platforms.

**Comment by rsdoiel** [comment]
Hi, thanks for writing. We're in the process of rebooting AuthorCarpentry under a new organization on Github at https://github.com/AuthorCarpentry. Can you subscribe to that?  We are planning on creating a lesson development repository under that organization. Would you like an invite?

Thanks, Robert

**Comment by rsdoiel** [comment]
Hello,

We are migrating this to the new Github organization for AuthorCarpentry at  https://github.com/AuthorCarpentry. I am closing this issue as part of that migration.

Thank you,

Robert
