### ISSUE TITLE
Connections between Author Carpentry and Other Scholarly Communication Programs

### ISSUE THREAD

**Issue by Repositorian** [caltechlibrary/AuthorCarpentry#3]
Author Carpentry draws on myriad teaching and digital literacy initiatives in scholarly communication, open access publishing and open science including:
- [Software Carpentry](http://software-carpentry.org/)
- [Data Carpentry](http://www.datacarpentry.org/)
- [The Programming Historian](http://programminghistorian.org/)
- [Mozilla Science Lab](https://science.mozilla.org/)
- [ACRL Intersections of Scholarly Communication and Information Literacy](http://acrl.ala.org/intersections/)
- [RDA/CODATA Summer Schools in Data Science in the Developing World WG](https://rd-alliance.org/groups/rdacodata-summer-schools-data-science-and-cloud-computing-developing-world.html)
- [UK Research Information Network's Working Group on information Handling](http://www.rin.ac.uk/our-work/researcher-development-and-skills/information-handling-training-researchers/working-group-i)

Are there are other programs we should consider in designing our curriculum, so as not to reinvent the wheel? Other partners to cultivate or consortia to take part in? All feedback and suggestions welcome!

**Comment by rsdoiel** [comment]
Migrated to https://github.com/AuthorCarpentry.
