### ISSUE TITLE
CODATA-RDA Summer School Author Carpentry Curriculum

### ISSUE THREAD

**Issue by Repositorian** [caltechlibrary/AuthorCarpentry#4]
The following lessons will be offered for testing and review at the CODATA-RDA Summer School for Research Data Scientists, August 1-12-2016. 

1.Creating and managing Open Reference Lists (citation metadata) with DOis and BibTeX
2. Populating and Curating ORCiD Profile using Open citation data (DOI's, BibTeX) and integrating ORCiD profile with scholarly reputation services (ImpactStory, OpenVIVO)
3. Scientific writing and bibliographies in LaTeX (Guest speaker: John Hammersley, Overleaf)
4. Open release/publication of research outputs using Creative Commons licenses and waivers (with brief summary of CODATA-Research Data Alliance recommendations on legal interoperability for research data and associated outputs)

**Comment by rsdoiel** [comment]
Migrated to https://github.com/AuthorCarpentry.
